#!/bin/bash -login
#PBS -l nodes=1:ppn=8,walltime=02:00:00,mem=32gb
#PBS -l feature='intel16',file=30gb
#PBS -N Trimm_
#PBS -j oe
#PBS -M pitchers@msu.edu
#PBS -m abe
#PBS -r n
#PBS -t 000-199

### 01_trimmomatic_array.qsub
#  – this script is called simply with `qsub 01_trimmomatic_array.qsub`
#  – this script globs in file that look like `XXX_NNNN_library_Lane_RX_001.fastq.gz`
#  - this script writes out `XXX_NNNN_library_Lane_RX_001_fastq` & `XXX_NNNN_library_Lane_RX_Ye.trimmed.fq`

#The JOBSCRIPT variable should be the name of _this_ script
JOBSCRIPT=01_trimmomatic_array.qsub

## Set up some variables
# where do the files live
dir=/mnt/ls15/scratch/groups/efish/WILL/Pipeline8/

# Current job number
n=${PBS_ARRAYID}

# build a list of file names
cd ${dir}
myfiles=(*_R1_001.fastq.gz)

# Set maximum number of jobs for this run
MAXJOBID=$( expr `echo ${#myfiles[@]}` - 1 )

# unzip the focal gzip archive and its mate-pair
gunzip -c ${myfiles[${n}]} > `basename ${myfiles[${n}]} .gz`
gunzip -c `basename ${myfiles[${n}]} _R1_001.fastq.gz`_R2_001.fastq.gz > `basename ${myfiles[${n}]} _R1_001.fastq.gz`_R2_001.fastq

# pull out one element of the array at a time based on n
thisname=`basename ${myfiles[${n}]} _R1_001.fastq.gz`

# load required modules
module load Trimmomatic/0.33
module load Java/1.8.0_31

# Trimmomatic command
if [ ! -f ${thisname}_R1_se.trimmed.fq ]
  then
  java -XX:ParallelGCThreads=8 -jar $TRIM/trimmomatic PE -threads 7 -phred33 ${thisname}_R1_001.fastq ${thisname}_R2_001.fastq \
          ${thisname}_R1_pe.trimmed.fq ${thisname}_R1_se.trimmed.fq ${thisname}_R2_pe.trimmed.fq ${thisname}_R2_se.trimmed.fq \
          ILLUMINACLIP:/mnt/research/efish/2015_genomic_data/Illumina_adapters.fa:2:30:10 LEADING:20 TRAILING:20 MAXINFO:50:0.5
fi

# Calculate next job to run
NEXT=$(( ${n} + 200 ))

#Check to see if next job is past the maximum job id, if so then submit the next unqueued job
if [ ${NEXT} -le ${MAXJOBID} ]
then
    cd ${PBS_O_WORKDIR}
    qsub -t ${NEXT} ${JOBSCRIPT}
fi

#Check to see if this is the last job, if so email me and submit the script for the next stage of the pipeline
if [ ${n} -eq ${MAXJOBID} ]
then
    echo "." | mail -s "The Trimmomatic array is finishing" ${USER}@msu.edu
    cd ${PBS_O_WORKDIR}
    qsub -v genome=illumina 02_alignment_array.qsub
    qsub -v genome=bionano  02_alignment_array.qsub
fi

#Print out the statistics for this job
qstat -f ${PBS_JOBID}
