#!/bin/bash -login
#PBS -l nodes=1:ppn=8,walltime=02:00:00,mem=32gb,feature='intel16'
#PBS -N Dedup_${PBS_ARRAYID}
#PBS -j oe
#PBS -M pitchers@msu.edu
#PBS -m abe
#PBS -r n
#PBS -t 0-200

#Set manximum number of jobs for this run
MAXJOBID=767

#The JOBSCRIPT variable should be the name of this script
JOBSCRIPT=deduplication_array.qsub

## Set up some variables
# where do the files live
dir=/mnt/ls15/scratch/groups/efish/WILL/Pipeline6
ref=/mnt/ls15/scratch/groups/efish/P_kings_genome/supercontigs.fasta

# Current job number
n=${PBS_ARRAYID}
# build a list of file names
cd ${dir}
filelist=(*.aligned.sam)
thisfile=${filelist[${n}]}

module load picardTools/1.89

# the PICARD commands – I could probably pipe then together, but this way less is lost if we crash
if [ ! -f `basename ${thisfile} .sam`.dedup.bam ]
	then java -jar ${PICARD}/SortSam.jar INPUT=${thisfile} OUTPUT=`basename ${thisfile} .sam`.sorted.sam SORT_ORDER=coordinate
		 java -jar ${PICARD}/MarkDuplicates.jar INPUT=`basename ${thisfile} .sam`.sorted.sam OUTPUT=`basename ${thisfile} .sam`.dedup.bam M=`basename ${thisfile} .sam`.metrics.txt
 		 java -jar ${PICARD}/BuildBamIndex.jar INPUT=`basename ${thisfile} .sam`.dedup.bam
fi

# Calculate next job to run
NEXT=$(( ${n} + 200 ))

#Check to see if next job is past the maximum job id
if [ ${NEXT} -le ${MAXJOBID} ]
then
    cd ${PBS_O_WORKDIR}
    qsub -t ${NEXT} ${JOBSCRIPT}
fi

#Check to see if this is the last job and email user
if [ ${n} -eq ${MAXJOBID} ]
then
    echo "." | mail -s "The PICARDTools JOB ARRAY is finishing" ${USER}@msu.edu
    cd ${PBS_O_WORKDIR}
    qsub 04_base_score_recalibration_array.qsub
fi

#Print out the statistics for this job
qstat -f ${PBS_JOBID}
