#!/bin/bash -login
#PBS -l nodes=1:ppn=8,walltime=04:00:00,mem=128gb
#PBS -l file=20gb,feature='intel16'
#PBS -N BaseR1_temp
#PBS -j oe
#PBS -M pitchers@msu.edu
#PBS -m abe
#PBS -r n
#PBS -t 000-647

#### 04_base_score_recalibration_array.qsub
#  – this script globs in files that look like `XXX_NNNN_library_Lane_RX_Ye.aligned.dedup.bam`
#  - this script writes out files that look like `XXX_NNNN_library_Lane_RX_Ye.aligned.dedup.recalibrated.bam`

## Set up some variables
# where do the files live
dir=/mnt/ls15/scratch/groups/efish/WILL/Pipeline7
ref=/mnt/ls15/scratch/groups/efish/P_kings_genome/supercontigs.fasta

# Current job number
n=${PBS_ARRAYID}

# build a list of file names
cd ${dir}
filelist=(*.aligned.dedup.bam)
thisfile=${filelist[${n}]}

# load needed modules
module load GATK/3.7.0
module load picardTools/1.89

## SPECIAL SAUCE - make temp scratch space to which to write outputs
OUTDIR=${TMPDIR}/BaseR
mkdir -p ${OUTDIR}
mkdir -p ${dir}/tempbams

cd ${OUTDIR}
df -h ${OUTDIR}

if [ ! -f tempbams/`basename ${thisfile} .bam`.recal_data.table ]
then
	## Analysze patterns of covariation in the dataset (~10 mins)
	java -Xmx120g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T BaseRecalibrator \
			-R ${ref} -I ${dir}/${thisfile} -o `basename ${thisfile} .bam`.recal_data.table \
			--run_without_dbsnp_potentially_ruining_quality  -nct 28  -rf BadCigar
fi

# copy output back to scratch
cp `basename ${thisfile} .bam`.recal_data.table ${dir}/tempbams/

if [ ! -f tempbams/`basename ${thisfile} .bam`.post_recal_data.table ]
	then
	## Do a second pass to analyze covariation remaining after recalibration (~10 mins)
	java -Xmx120g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T BaseRecalibrator \
			-R ${ref} -I ${dir}/${thisfile}  -BQSR `basename ${thisfile} .bam`.recal_data.table \
			-o `basename ${thisfile} .bam`.post_recal_data.table \
			--run_without_dbsnp_potentially_ruining_quality  -nct 28 -rf BadCigar
fi

# copy output back to scratch
cp `basename ${thisfile} .bam`.post_recal_data.table ${dir}/tempbams/


cd ${PBS_O_WORKDIR}
NEXTJOB=`qsub -t ${n} 05_base_score_recal_array2.qsub`
echo this is job ${PBS_JOBID} ${n} submitting ${n} ${NEXTJOB}
echo `date`

#Print out the statistics for this job
qstat -f ${PBS_JOBID}
