#!/bin/bash -login
#PBS -l nodes=1:ppn=8,walltime=04:00:00,mem=62gb,feature='intel16'
#PBS -N BaseR_${PBS_ARRAYID}
#PBS -j oe
#PBS -M pitchers@msu.edu
#PBS -m abe
#PBS -r n
#PBS -t 0-200

# The JOBSCRIPT variable should be the name of this script
JOBSCRIPT=04_base_score_recalibration_array.qsub

## Set up some variables
# where do the files live
# dir=/mnt/ls15/scratch/groups/efish/WILL/Pipeline6/
dir=/mnt/ls15/scratch/groups/efish/WILL/Pipeline7/
ref=/mnt/ls15/scratch/groups/efish/P_kings_genome/supercontigs.fasta

# Current job number
n=${PBS_ARRAYID}

# build a list of file names
cd ${dir}
filelist=(*.aligned.dedup.bam) 
thisfile=${filelist[${n}]}

# Set maximum number of jobs for this run
MAXJOBID=`echo ${#filelist[@]}`

module load GATK/3.7.0

if [ ! -f `basename ${thisfile} .bam`.recal_data.table ]
then
	## Analysze patterns of covariation in the dataset (~10 mins)
	java -Xmx60g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T BaseRecalibrator \
			-R ${ref} -I ${thisfile} -o `basename ${thisfile} .bam`.recal_data.table \
			--run_without_dbsnp_potentially_ruining_quality  -nct 8
fi

if [ ! -f `basename ${thisfile} .bam`.post_recal_data.table ]
	then
	## Do a second pass to analyze covariation remaining after recalibration (~10 mins)
	java -Xmx60g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T BaseRecalibrator \
			-R ${ref} -I ${thisfile}  -BQSR `basename ${thisfile} .bam`.recal_data.table \
			-o `basename ${thisfile} .bam`.post_recal_data.table \
			--run_without_dbsnp_potentially_ruining_quality  -nct 8
fi

if [ ! -f `basename ${thisfile} .bam`.recal_plots.pdf ]
	then
	## Generate before-after plots (~5 mins)
	java -Xmx60g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T AnalyzeCovariates \
			-R ${ref}  -before `basename ${thisfile} .bam`.recal_data.table \
			-after `basename ${thisfile} .bam`.post_recal_data.table \
			-plots `basename ${thisfile} .bam`.recal_plots.pdf
fi

if [ ! -f `basename ${thisfile} .bam`.recalibrated.bam ]
	then
	## Apply the recalibration to the sequence data (~5 mins)
	java -Xmx60g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T PrintReads -R ${ref} \
			-I ${thisfile}  -BQSR `basename ${thisfile} .bam`.recal_data.table \
			-o `basename ${thisfile} .bam`.recalibrated.bam  -nct 8
fi

# Calculate next job to run
NEXT=$(( ${n} + 200 ))

#Check to see if next job is past the maximum job id
if [ ${NEXT} -le ${MAXJOBID} ]
then
    cd ${PBS_O_WORKDIR}
    qsub -t ${NEXT} ${JOBSCRIPT}
fi

#Check to see if this is the last job and email user
if [ ${n} -eq ${MAXJOBID} ]
then
    echo "." | mail -s "The base_score_recalibration JOB ARRAY is finishing" ${USER}@msu.edu
	zip base_recal_plots.zip *recal_plots.pdf
    cd ${PBS_O_WORKDIR}
#	qsub 05_bam_merge_samples_array.qsub
fi

#Print out the statistics for this job
qstat -f ${PBS_JOBID}
