#!/bin/bash -login
#PBS -l nodes=1:ppn=4,walltime=04:00:00,mem=60gb
#PBS -o /mnt/research/efish/2015_genomic_data/scripts
#PBS -N merge_all_vcfs
#PBS -j oe
#PBS -M pitchers@msu.edu
#PBS -m abe
#PBS -l file=200gb
#PBS -r n

## Set up some variables
# where do the files live
#dir=/mnt/scratch/pitchers/eFISH/Analysis/
dir=/mnt/ls15/scratch/groups/efish/WILL/Pipeline7/V7_chunks
ref=/mnt/ls15/scratch/groups/efish/P_kings_genome/supercontigs.fasta

cd ${dir}
mkdir -p ../Assoc

# load modules
module load Java/1.8.0_31
#module load Java/jdk1.8.0

sample_list=(all_fish_vcf_slice_*.vcf)
samples=`for i in "${sample_list[@]}" ; do echo --variant ${i} ; done | xargs`


java -Xmx60g -Djava.io.tmpdir=${TMPDIR} -cp /mnt/home/pitchers/GenomeAnalysisTK.jar \
							org.broadinstitute.gatk.tools.CatVariants \
							-R ${ref} ${samples} -out ../Assoc/all_fish_version_7.vcf


mv all_fish_version_6-1.vcf  ../Assoc/

# email user & start the next job
	echo "." | mail -s "The vcf_all_merge job is finished" ${USER}@msu.edu
	cd $PBS_O_WORKDIR
	# qsub 09_vcf_disco_chunk_5-2_array.qsub
	# qsub -v 10_vcf_genotype_chunk_6-2_array.qsub
#	qsub -v all_fish_version_6-1 vcf_filter.qsub

#Print out the statistics for this job
qstat -f ${PBS_JOBID}
