#!/bin/bash -login
#PBS -l nodes=1:ppn=2,walltime=02:00:00,mem=32gb
#PBS -l feature='intel16'
#PBS -N GVCFgeno
#PBS -j oe
#PBS -M pitchers@msu.edu
#PBS -m abe
#PBS -r n
#PBS -t 1-10

#### 09_genotype_gvcf.qsub
#  -
#  – this script globs in files that look like `XXX_NNNN_all_libraries.bam`
#  - this script writes out *lots* of files that look like `all_fish_slice_N.g.vcf`


# Current job number
n=${PBS_ARRAYID}

#The JOBSCRIPT variable should be the name of this script
JOBSCRIPT=09_genotype_gvcfs.qsub

# where do the files live
dir=/mnt/ls15/scratch/groups/efish/WILL/Pipeline8/bionano
ref=/mnt/ls15/scratch/groups/efish/P_kings_SuperScafGenome/Para_king_2015_013_20_40_15_90_3_superscaffold.fasta

cd ${dir}

module load Java/1.8.0_31
module load GATK/3.7.0


# build a list of file names
thesefiles=(*all_libraries.g.vcf)
thesefish=`for i in "${thesefiles[@]}" ; do echo --variant ${i} ; done | xargs`

MAXJOBID=`wc -l superscaf.indices | cut -d' ' -f 1`
thisscaffold=`head -${n} superscaf.indices | tail -1`


# the call to the GATK GenotypeGVCFs
java -Xmx60g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T GenotypeGVCFs \
              -R $ref  ${thesefish}  -o output_part_${n}.vcf ${thisscaffold} \
              --disable_auto_index_creation_and_locking_when_reading_rods


# Calculate next job to run
NEXT=$(( ${n} + 10 ))

# Check to see if next job is past the maximum job id
if [ ${NEXT} -le ${MAXJOBID} ]
then
    cd ${PBS_O_WORKDIR}
    qsub -t ${NEXT} ${JOBSCRIPT}
fi

# Check to see if this is the last job and email user
# the last job is NOT always the last one to *finish* -- I ought to make this more reliable....
if [ ${n} -eq ${MAXJOBID} ]
then
    echo "." | mail -s "The vcf_genotype job is finishing" ${USER}@msu.edu
    cd ${PBS_O_WORKDIR}
#    qsub 08_merge_all_vcfs.qsub
fi

#Print out the statistics for this job
qstat -f ${PBS_JOBID}
