#!/bin/bash -login
#PBS -l nodes=1:ppn=28,walltime=04:00:00,mem=128gb
#PBS -l feature='intel16'
#PBS -o /mnt/research/efish/2015_genomic_data/scripts
#PBS -N merge_all_vcfs
#PBS -j oe
#PBS -M pitchers@msu.edu
#PBS -m abe
#PBS -r n

#### 09a_merge_all_vcfs.qsub
#  – this script needs to be called like this: `qsub -v genome=illumina gvcf=HC 09a_merge_all_vcfs.qsub`
#  – this script globs in a pile of files that look like e.g. `all_fish_illumina_scafindex_N.vcf`
#  - this script writes out 1 big file called `all_fish_v8_illumina_HC.vcf`

## Set up some variables -- where do the files live
topdir=/mnt/ls15/scratch/groups/efish/WILL/Pipeline8

if [ ${genome} == "bionano" ]
  then
    dir=${topdir}/bionano
    ref=/mnt/ls15/scratch/groups/efish/P_kings_SuperScafGenome/Para_king_2015_013_20_40_15_90_3_superscaffold.fasta
  else
    dir=${topdir}/illumina
    ref=/mnt/ls15/scratch/groups/efish/P_kings_genome/supercontigs.fasta
fi

cd ${dir}
mkdir -p ../Assoc

# load modules
module load Java/1.8.0_31
module load GATK/3.7.0
localGATK=/mnt/research/efish/2015_genomic_data/GATK/GenomeAnalysisTK.jar

sample_list=(all_fish_${genome}_scafindex_*.vcf)
samples=`for i in "${sample_list[@]}" ; do echo --variant ${i} ; done | xargs`

if [ ${gvcf} == "GVCF" ]
  then
    cd GVCF_called
  else
    cd HC_called
fi

# join all the vcf chunks together
java -Xmx120g -Djava.io.tmpdir=${TMPDIR} -cp ${localGATK}  org.broadinstitute.gatk.tools.CatVariants \
              -R ${ref} ${samples} -out ../Assoc/all_fish_v8_${genome}_${gvcf}.vcf


# validation check on the output vcf
java -Xmx120g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T ValidateVariants -R ${ref} --validationTypeToExclude ALL \
              -V ../Assoc/all_fish_v8_${genome}_${gvcf}.vcf


# email user & start the next job
    echo "." | mail -s "The vcf_all_merge job is finished" ${USER}@msu.edu
    cd $PBS_O_WORKDIR


#Print out the statistics for this job
qstat -f ${PBS_JOBID}
