#!/bin/bash -login
#PBS -l nodes=1:ppn=1,walltime=10:00:00,mem=16gb
#PBS -o /mnt/research/efish/2015_genomic_data/scripts
#PBS -N BreakDancer
#PBS -j oe
#PBS -M pitchers@msu.edu
#PBS -m abe
#PBS -r n

## Set up some variables
dir=/mnt/scratch/pitchers/eFISH/Analysis/
ref=/mnt/scratch/pitchers/eFISH/P_kings_genome/supercontigs.fasta

# load modules
cd ${dir}
module load SAMTools/1.2
module load BreakDancer/1.1.2

ls -lathr *analysis.cfg

# set up a configuration file
# bamfiles=*libraries.bam
bamfiles=*recalibrated.bam
bam2cfg.pl -g -h ${bamfiles} > breakdancer_`date '+%d_%m_%Y'`_analysis.cfg

ls -lathr *analysis.cfg

# run breakdancer
filename=breakdancer_`date '+%d_%m_%Y'`_analysis
breakdancer-max -t -q 10 -d ${filename}.ctx ${filename}.cfg > ${filename}.ctx

echo "." | mail -s "The BreakDancer JOB is finishing" ${USER}@msu.edu

cd $PBS_O_WORKDIR
qstat -f ${PBS_JOBID}
