#!/bin/bash -login
#PBS -l nodes=1:ppn=4,walltime=2:00:00,mem=32gb
#PBS -N calc_Fsts
#PBS -j oe
#PBS -M pitchers@msu.edu
#PBS -m abe
#PBS -r n

## Set up some variables
# where do the files live
dir=/mnt/ls15/scratch/groups/efish/WILL/Pipeline6/Assoc
popdir=/mnt/research/efish/2015_genomic_data/Populations/

# load modules
cd ${dir}
module load vcftools/0.1.14

vcftools --vcf ${input_data}.vcf --TajimaD 5000

# Email user
echo "." | mail -s "The TajD job is finishing" ${USER}@msu.edu
cd ${PBS_O_WORKDIR}

#Print out the statistics for this job
qstat -f ${PBS_JOBID}
