#!/bin/bash -login
#PBS -o /mnt/research/efish/2015_genomic_data/scripts
#PBS -l nodes=1:ppn=1,walltime=04:00:00,mem=64gb
#PBS -N PLINK_fisher
#PBS -j oe
#PBS -M pitchers@msu.edu
#PBS -m abe
#PBS -r n

#dir=/mnt/scratch/pitchers/eFISH/Analysis/
dir=/mnt/ls15/scratch/groups/efish/WILL/V5-1_chunks/
# dir=/mnt/ls15/scratch/groups/efish/WILL/V5-1_chunks/

cd $dir

module load R/3.2.0
module load plink/1.9
module load vcftools/0.1.12a

# mydata=`basename all_variants_merged_27_10_2015.vcf .vcf`
# mydata=all_variants_merged_21_01_2016
# output_name=${input_data}_g50_CI

R --no-save < ${PBS_O_WORKDIR}/AssocComparison.R


# grab scaffold & SNP ID

cut -d',' -f 1-2 fisher_all_fish_version_5-1_HPC_geno50.assoc.csv | tr ',' '\t' > temp
vcftools --vcf all_fish_version_5-1_HPC.vcf --positions temp --extract-FORMAT-info GT -c > fisher_top_SNPs


# grab scaffold & SNP ID – 3 level pheno

cut -d',' -f 1-2 3level_all_fish_version_5-1_HPC_3level.assoc.csv | tr ',' '\t' > temp
vcftools --vcf all_fish_version_5-1_HPC.vcf --positions temp --extract-FORMAT-info GT -c > 3level_top_SNPs


# grab scaffold & SNP ID – 3 level pheno with pop covariate

cut -d',' -f 1-2 PopCov_P0_all_fish_version_5-1_HPC_3level_PopCov.assoc.logistic.csv | tr ',' '\t' > temp
vcftools --vcf all_fish_version_5-1_HPC.vcf --positions temp --extract-FORMAT-info GT -c > PopCov_3level_top_SNPs


# grab scaffold & SNP ID – 2 level case/control with pop stratification

cut -d',' -f 1-2 all_fish_version_5-1_HPC_strata.assoc | tr ',' '\t' > temp
vcftools --vcf all_fish_version_5-1_HPC.vcf --positions temp --extract-FORMAT-info GT -c > strata_top_SNPs


# grab scaffold & SNP ID - 3 level with mid- and present levels collapsed

cut -d',' -f 1-2 3levelsas2_all_fish_version_5-1_HPC_3levelasas2ssoc.csv | tr ',' '\t' > temp
vcftools --vcf all_fish_version_5-1_HPC.vcf --positions temp --extract-FORMAT-info GT -c > 3levelsas2_top_SNPs

###

hypoth=( GENO ALLELIC DOM REC TREND )
for i in ${hypoth[@]}
  do cut -d',' -f 1-2 model_all_fish_version_5-1_HPC_g50_CI.${i}.model.reformatted.csv | tr ',' '\t' > temp
	vcftools --vcf all_fish_version_5-1_HPC.vcf --positions temp --extract-FORMAT-info GT -c > ${i}_top_SNPs
	rm temp
done

# grab scaffold & SNP ID for alternate analysis

cut -d',' -f 1-2 fisher_without_COB_5-1_HPC.2017_geno50.assoc.csv | tr ',' '\t' > temp
vcftools --vcf without_COB_5-1_HPC.2017.vcf --positions temp --extract-FORMAT-info GT -c > fisher_no_COB_top_SNPs


for i in ${hypoth[@]}
  do cut -d',' -f 1-2 model_without_COB_5-1_HPC.2017_g50_CI.${i}.model.reformatted.csv | tr ',' '\t' > temp
	vcftools --vcf without_COB_5-1_HPC.2017.vcf --positions temp --extract-FORMAT-info GT -c > ${i}_no_COB_top_SNPs
	rm temp
done
