#!/bin/bash -login
#PBS -o /mnt/research/efish/2015_genomic_data/scripts
#PBS -l nodes=1:ppn=1,walltime=04:00:00,mem=30gb
#PBS -N GetTopSNPs
#PBS -j oe
#PBS -M pitchers@msu.edu
#PBS -m abe
#PBS -r n

dir=/mnt/ls15/scratch/groups/efish/WILL/Pipeline7/Assoc
ref=/mnt/ls15/scratch/groups/efish/P_kings_genome/supercontigs.fasta

cd $dir
module load GNU/4.9
module load R/3.3.2
module load GATK/3.7.0

AssocFileList=( ${input_data}*.assoc.fisher )
# AssocFileList=( ${input_data}*_mperm.assoc.logistic )


for thisfile in ${AssocFileList[@]}
	do  Rscript ${PBS_O_WORKDIR}/GetTopSNPs.R ${thisfile} # this script needs to be adjusted

	# grab scaffold & SNP ID
	# cut -d',' -f 2 ${thisfile}.topsnps.csv | tail -n +2 | sed s/Var-//g | tr '-' ':'  > ${thisfile}.intervals
	cut -d',' -f 1,2 ${thisfile}.topsnps.csv | tail -n +2 | tr ',' ':'  > ${thisfile}.intervals

	# pull out relevant lines from vcf file
java -Xmx30g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T SelectVariants \
-V ${input_data}.vcf \
-o ${thisfile}.topSNPs.vcf \
-R ${ref} -L ${thisfile}.intervals

java -Xmx30g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T VariantsToTable \
-V ${thisfile}.topSNPs.vcf \
-F CHROM -F POS -F REF -F ALT -GF GT -R ${ref} \
-o ${thisfile}.topSNPs.table

	rm ${thisfile}.intervals  ${thisfile}.topSNPs.vcf  ${thisfile}.topSNPs.vcf.idx
done


AssocModelFileList=( ${input_data}*.model.reformatted.csv )

for thisfile in ${AssocModelFileList[@]}
	do Rscript ${PBS_O_WORKDIR}/GetTopSNPs.R ${thisfile}

	# grab scaffold & SNP ID
	cut -d',' -f 2 ${thisfile} | tail -n +2 | sed s/Var-//g | tr '-' ':' > `basename ${thisfile} .csv`.intervals

	 # pull out relevant lines from vcf file
	 java -Xmx30g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T SelectVariants \
								-V ${input_data}.vcf \
								-o `basename ${thisfile} .csv`.topSNPs.vcf \
								-R ${ref} -L `basename ${thisfile} .csv`.intervals

	java -Xmx30g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T VariantsToTable \
							-V `basename ${thisfile} .csv`.topSNPs.vcf \
							-F CHROM -F POS -F REF -F ALT -GF GT -R ${ref} \
							-o `basename ${thisfile} .csv`.topSNPs.table

	rm `basename ${thisfile} .csv`.intervals  `basename ${thisfile} .csv`.topSNPs.vcf  `basename ${thisfile} .csv`.topSNPs.vcf.idx
done

#Print out the statistics for this job
cd ${PBS_O_WORKDIR}
qstat -f ${PBS_JOBID}
