#!/bin/bash -login
#PBS -o /mnt/research/efish/2015_genomic_data/scripts
#PBS -l nodes=1:ppn=1,walltime=04:00:00,mem=30gb
#PBS -N GetTopSNPs
#PBS -j oe
#PBS -M pitchers@msu.edu
#PBS -m abe
#PBS -r n

ref=/mnt/scratch/pitchers/eFISH/P_kings_genome/supercontigs.fasta

#dir=/mnt/scratch/pitchers/eFISH/Analysis/
dir=/mnt/ls15/scratch/groups/efish/WILL/V5-1_chunks/
# dir=/mnt/ls15/scratch/groups/efish/WILL/V5-1_chunks/

cd $dir

module load GNU/4.9
module load R/3.3.2
module load GATK/3.5.0

AssocFileList=( ${input_data}*.assoc.fisher )

for thisfile in ${AssocFileList[@]}
	do Rscript ${PBS_O_WORKDIR}/GetTopSNPs.R ${thisfile}

	# grab scaffold & SNP ID
	cut -d',' -f 1-2 ${thisfile}.csv | tr ',' '\t' | tail -n +2 | tr '\t' ':'  > temp.intervals

	# pull out relevant lines from vcf file
	java -Xmx30g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T SelectVariants \
						    -V ${input_data}.vcf \
							-o ${input_data}_topSNPs.vcf \
#							-R ${ref} -L temp.intervals
							-R ${ref} --keepIDs temp.intervals

	java -Xmx30g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T VariantsToTable \
		                    -V ${input_data}_topSNPs.vcf \
							-F CHROM -F POS -GF GT -R ${ref} \
							-o `basename ${thisfile} .assoc.fisher`_topSNPs.table
	rm temp.intervals
done


AssocModelFileList=( ${input_data}*.model.reformatted.csv )

for thisfile in ${AssocModelFileList[@]}
	do Rscript ${PBS_O_WORKDIR}/GetTopSNPs.R ${thisfile}

	# grab scaffold & SNP ID
    cut -d',' -f 1-2 top_250_${thisfile} | tail -n +2 | tr ',' ':'  > temp.intervals

	 # pull out relevant lines from vcf file
    java -Xmx30g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T SelectVariants \
                            -V ${input_data}.vcf \
                            -o ${input_data}_topSNPs.vcf \
#                            -R ${ref} -L temp.intervals
							-R ${ref} --keepIDs temp.intervals

    java -Xmx30g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T VariantsToTable \
                            -V ${input_data}_topSNPs.vcf \
                            -F CHROM -F POS -GF GT -R ${ref} \
                            -o `basename ${thisfile} .assoc.fisher`_topSNPs.table
	rm temp.intervals
done



#Print out the statistics for this job
cd ${PBS_O_WORKDIR}
qstat -f ${PBS_JOBID}



