#!/bin/bash -login
#PBS -o /mnt/research/efish/2015_genomic_data/scripts
#PBS -l nodes=1:ppn=1,walltime=04:00:00,mem=30gb
#PBS -N GetTopSNPs
#PBS -j oe
#PBS -M pitchers@msu.edu
#PBS -m abe
#PBS -r n

dir=/mnt/ls15/scratch/groups/efish/WILL/Pipeline6/V6-1_chunks/
ref=/mnt/ls15/scratch/groups/efish/P_kings_genome/supercontigs.fasta


cd $dir

module load GNU/4.9
module load R/3.3.2
module load GATK/3.7.0

#AssocFileList=( ${input_data}*.assoc.fisher )
AssocFileList=( ${input_data}*.assoc.logistic )

for thisfile in ${AssocFileList[@]}
	do Rscript ${PBS_O_WORKDIR}/GetTopSNPs.R ${thisfile} # this script needs to be adjusted

	# grab scaffold & SNP ID
	cut -d',' -f 2 ${thisfile}.csv | tr ',' '\t' | tail -n +2 | sed s/Var-//g | tr '-' ':'  > ${thisfile}.intervals

	# pull out relevant lines from vcf file
	java -Xmx30g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T SelectVariants \
							-V ${input_data}.vcf \
							-o ${input_data}_topSNPs.vcf \
							-R ${ref} -L ${thisfile}.intervals

	java -Xmx30g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T VariantsToTable \
		                    -V ${input_data}_topSNPs.vcf \
							-F CHROM -F POS -F REF -F ALT -GF GT -R ${ref} \
							-o `basename ${thisfile} .assoc.fisher`_topSNPs.table
	rm ${thisfile}.intervals
done


AssocModelFileList=( ${input_data}*.model.reformatted.csv )

for thisfile in ${AssocModelFileList[@]}
	do Rscript ${PBS_O_WORKDIR}/GetTopSNPs.R ${thisfile}

	# grab scaffold & SNP ID
    cut -d',' -f 1-2 top_250_${thisfile} | tail -n +2 | tr ',' ':'  > ${thisfile}.intervals

	 # pull out relevant lines from vcf file
    java -Xmx30g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T SelectVariants \
                            -V ${input_data}.vcf \
                            -o ${input_data}_topSNPs.vcf \
							-R ${ref} -L ${thisfile}.intervals

    java -Xmx30g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T VariantsToTable \
                            -V ${input_data}_topSNPs.vcf \
                            -F CHROM -F POS -F REF -F ALT -GF GT -R ${ref} \
                            -o `basename ${thisfile} .model.reformatted.csv`_topSNPs.table
	rm ${thisfile}.intervals
done



#Print out the statistics for this job
cd ${PBS_O_WORKDIR}
qstat -f ${PBS_JOBID}
