#!/bin/bash -login
#PBS -l nodes=1:ppn=4,walltime=03:00:00,mem=32gb
#PBS -N vcf_merge
#PBS -j oe
#PBS -M pitchers@msu.edu
#PBS -m abe
#PBS -r n

## Set up some variables
# where do the files live
dir=/mnt/scratch/pitchers/eFISH/Illumina_2015/GATK-compatible/

# build a list of file names
cd ${dir}

module load tabix/0.2.6
module load vcftools/4.2

# pre-processing for vcftools compatibility
for file in *.raw_variants.vcf
	do bgzip -c ${file} > ${file}.gz
	tabix ${file}.gz
done

# the call to VCF tools
# 1st merge step
for sample in *_L001_R1_pe.raw_variants.vcf.gz
	do vcf-merge --remove-duplicates `basename ${sample} _L001_R1_pe.raw_variants.vcf.gz`*vcf.gz | bgzip -c > `basename ${sample} _L001_R1_pe.raw_variants.vcf.gz`.merged.vcf.gz
	tabix `basename ${sample} _L001_R1_pe.raw_variants.vcf.gz`.merged.vcf.gz
done

# 2nd merge step
	vcf-merge --remove-duplicates *.merged.vcf.gz | bgzip -c > merged_output_`date '+%d_%m_%Y'`.vcf.gz

# email user
	echo "." | mail -s "The vcf_merge is finished" ${USER}@msu.edu

#Print out the statistics for this job
cd $PBS_O_WORKDIR
qstat -f ${PBS_JOBID}
