#!/bin/bash -login
#PBS -l nodes=1:ppn=1,walltime=45:00:00,mem=16gb
#PBS -o /mnt/research/efish/2015_genomic_data/scripts
#PBS -N merge_all_bams
#PBS -j oe
#PBS -M pitchers@msu.edu
#PBS -m abe
#PBS -r n

## Set up some variables
# where do the files live
dir=/mnt/scratch/pitchers/eFISH/Analysis/
ref=/mnt/scratch/pitchers/eFISH/P_kings_genome/supercontigs.fasta

# load modules
cd ${dir}
module load samtools/1.2

# call to samtools
samtools merge all_bam_merged_recal_`date '+%d_%m_%Y'`.bam *_all_merged.bam

# email user & start the next job
echo "." | mail -s "The bam_all_merge job is finished" ${USER}@msu.edu
cd $PBS_O_WORKDIR
#input_data=all_variants_merged_`date '+%d_%m_%Y'`.vcf
#qsub -V vcf_discovery.qsub

#Print out the statistics for this job
qstat -f ${PBS_JOBID}
