#!/bin/bash -login
#PBS -l nodes=1:ppn=4,walltime=04:00:00,mem=60gb
#PBS -o /mnt/research/efish/2015_genomic_data/scripts
#PBS -N merge_all_vcfs
#PBS -j oe
#PBS -M pitchers@msu.edu
#PBS -m abe
#PBS -l file=200gb
#PBS -r n

## Set up some variables
# where do the files live
#dir=/mnt/scratch/pitchers/eFISH/Analysis/
dir=/mnt/ls15/scratch/groups/efish/WILL/Pipeline6
ref=/mnt/ls15/scratch/groups/efish/P_kings_genome/supercontigs.fasta

#mytempdir=/mnt/research/efish/2015_genomic_data/

# load modules
cd ${dir}

module load Java/1.8.0_31

cd V5-1_chunks/

#sample=(*libraries.vcf)
#sample=(all_fish*slice*.vcf)
#samples=`for i in $(seq 1 2765) ; do echo --variant all_fish_slice_${i}.vcf ; done | xargs`
samples=`for i in $(ls all_fish_*_slice_*.vcf) ; do echo --variant ${i} ; done | xargs`


java -Xmx60g -Djava.io.tmpdir=${TMPDIR} -cp /mnt/home/pitchers/GenomeAnalysisTK.jar org.broadinstitute.gatk.tools.CatVariants -R ${ref} ${samples} -out all_fish_version_6-1.vcf 


# email user & start the next job
echo "." | mail -s "The vcf_all_merge job is finished" ${USER}@msu.edu
cd $PBS_O_WORKDIR
#input_data=all_variants_merged_`date '+%d_%m_%Y'`.vcf
#qsub -V calc_Fst_array.qsub

#Print out the statistics for this job
qstat -f ${PBS_JOBID}
