#!/bin/bash -login
#PBS -o /mnt/research/efish/2015_genomic_data/scripts
#PBS -l nodes=1:ppn=1,walltime=04:00:00,mem=32gb
#PBS -N PLINK_ASSOC
#PBS -j oe
#PBS -M pitchers@msu.edu
#PBS -m abe
#PBS -r n

#dir=/mnt/scratch/pitchers/eFISH/Analysis/
dir=/mnt/ls15/scratch/groups/efish/WILL/Pipeline6/Assoc/
#dir=/mnt/ls15/scratch/groups/efish/WILL/V5-2_chunks/

cd $dir

module load plink/1.9
#module load vcftools/0.1.12a

# make plink-format files from vcf
#vcftools --vcf ${input_data}.vcf --out ${input_data} --plink

# derive a simple lookup table from the *NEW* phenotype file; `ultimate_phenotype.txt` (P0-Absent=1, P0-Present=2)
if [ ! -f ../individual.list ]
  then tail -63 /mnt/research/efish/2015_genomic_data/ultimate_phenotype.txt | cut -f 1,2 | sed 's/P0-Present/2/g' | sed 's/P0-Absent/1/g' | sed 's/[\t ]\+/ /g' | sed 's/[A-Z]\{3,4\}_//g' > ../individual.list

  ### seq. data filenames contain a typo; IVI_3923 should have been IVI_4923 (discovered 23/02/2016)
  ### this line alters the phenotype lookup table so that the mis-named reads get the correct phenotype.
  sed -i s/4923/3923/ ../individual.list
fi

#python $PBS_O_WORKDIR/pheno_lookup.py ../individual.list ${input_data}.ped ${input_data}.ped.out
#mv ${input_data}.ped.out ${input_data}.ped

# make new bed fileset
#plink --file ${input_data} --out ${input_data} --make-bed --allow-extra-chr


# PLINK command with:
#  `--allow-no-sex` because our fishes' weren't sexed
#  `--geno` 0.50 requires a min. 50% genotyping rate
#  `--allow-extra-chr` required because our assembly has 1000's of scaffolds
#  `--assoc` calls reports for a quantitative phenotype
#  `--ci 0.95` to report 95% confidence intervals on odds ratios
#  `--pfilter 1` cuts out rows with p-vals >1 (i.e. strips 'NA's)
#  `--test-missing` Fisher's exact test for non-random missingness across cases/controls (separate output)
#  `--real-ref-alleles` "Specifies that A2 alleles are based on a real reference genome"...
plink --bfile ${input_data} --allow-no-sex --geno 0.50 --allow-extra-chr --assoc fisher --ci 0.95 --pfilter 1 --test-missing --real-ref-alleles --out ${input_data}

####
echo "." | mail -s "The PLINK assoc job is finishing" ${USER}@msu.edu
cd ${PBS_O_WORKDIR}
#    qsub nextjerb

#Print out the statistics for this job
qstat -f ${PBS_JOBID}


