#!/bin/bash -login
#PBS -l nodes=1:ppn=1,walltime=04:00:00,mem=60gb
#PBS -N plink_prep
#PBS -o /mnt/research/efish/2015_genomic_data/scripts
#PBS -j oe
#PBS -M pitchers@msu.edu
#PBS -m abe
#PBS -r n

## Set up some variables
# where do the files live
#dir=/mnt/ls15/scratch/groups/efish/WILL/Pipeline8
dir=/mnt/ls15/scratch/groups/efish/WILL/Pipeline8/bionano


# load modules
cd ${dir}
module load vcftools/0.1.14

#sed -i s/"fileformat=VCFv4.2"/"fileformat=VCFv4.1"/ ${input_data}.vcf

vcftools --vcf ${input_data}.vcf --out ${input_data} --plink

#awk -F "[\t ]" '{ $2=$1 "_" $2; print $1 "\t" $2 "\t" $3 "\t" $4 }' ${input_data}.map > temp.map
#mv temp.map ${input_data}.map

# email user & start the next job
echo "." | mail -s "the plink_prep job is finished" ${USER}@msu.edu
cd $PBS_O_WORKDIR
# qsub plink_pheno.qsub -v input_data=${input_data}
qsub plink_ind_pheno.qsub -v input_data=${input_data}

#Print out the statistics for this job
qstat -f ${PBS_JOBID}
