#!/bin/bash -login
#PBS -o /mnt/research/efish/2015_genomic_data/scripts
#PBS -l nodes=1:ppn=1,walltime=02:00:00,mem=16gb,feature='intel16'
#PBS -N plink_ind_pheno
#PBS -j oe
#PBS -M pitchers@msu.edu
#PBS -m abe
#PBS -r n

#dir=/mnt/scratch/pitchers/eFISH/Analysis/
dir=/mnt/ls15/scratch/groups/efish/WILL/

cd $dir

# mydata=`basename all_variants_merged_27_10_2015.vcf .vcf`
# mydata=all_variants_merged_21_01_2016
# instead, now call with `qsub plink_ind_pheno.qsub -v input_data=insertnamehere`

# derive a simple lookup table from the phenotype file (P0 absent=1, P0 present=2)
if [ ! -f individual.list ]
  then cat /mnt/research/efish/2015_genomic_data/specimens_for_genome_reseq.txt | tail -67 | cut -f 1,11 | sed 's/[yesYES]\{3\}/2/g' | sed 's/[noNO]\{2\}/1/g' | sed 's/[\t ]\+/ /g' > individual.list

  ### seq. data filenames contain a typo; IVI_3923 should have been IVI_4923 (discovered 23/02/2016)
  ### this line alters the phenotype lookup table so that the mis-named reads get the correct phenotype.
  sed -i s/4923/3923/ individual.list
  sed -i s/4007/4027/ individual.list
fi

cd V5-1_chunks/

# call my python script to write the phenotype codes into the .ped file
python $PBS_O_WORKDIR/pheno_lookup.py ../individual.list ${input_data}.ped ${input_data}.ped.out

mv ${input_data}.ped.out ${input_data}.ped

echo "." | mail -s "The PLINK pheno job is finishing" ${USER}@msu.edu
cd ${PBS_O_WORKDIR}
qsub plink_bed.qsub -v input_data=${input_data}

#Print out the statistics for this job
qstat -f ${PBS_JOBID}
