#!/bin/bash -login
#PBS -l nodes=1:ppn=1,walltime=03:00:00,mem=16gb
#PBS -N plink_prep
#PBS -o /mnt/research/efish/2015_genomic_data/scripts
#PBS -j oe
#PBS -M pitchers@msu.edu
#PBS -m abe
#PBS -r n

## Set up some variables
# where do the files live
dir=/mnt/scratch/pitchers/eFISH/Analysis/
ref=/mnt/scratch/pitchers/eFISH/P_kings_genome/supercontigs.fasta

# load modules
cd ${dir}

module load vcftools/4.2
module load plink/1.07

# input_data=all_variants_merged_27_10_2015
# input_data=all_variants_merged_21_01_2016

vcftools --vcf ${input_data}.vcf --out ${input_data} --plink

# email user & start the next job
echo "." | mail -s "the plink_prep job is finished" ${USER}@msu.edu
cd $PBS_O_WORKDIR
# qsub plink_pheno.qsub -v input_data=${input_data}
qsub plink_ind_pheno.qsub -v input_data=${input_data}

#Print out the statistics for this job
qstat -f ${PBS_JOBID}
