#!/bin/bash -login
#PBS -o /mnt/research/efish/2015_genomic_data/scripts
#PBS -l nodes=1:ppn=1,walltime=04:00:00,mem=64gb
#PBS -N PLINK_fisher
#PBS -j oe
#PBS -M pitchers@msu.edu
#PBS -m abe
#PBS -r n

#dir=/mnt/scratch/pitchers/eFISH/Analysis/
dir=/mnt/ls15/scratch/groups/efish/WILL/V5-1_chunks/

cd $dir

module load plink/1.9
module load vcftools/0.1.12a

# make plink file versions
vcftools --vcf ${input_data}.vcf --out ${input_data} --plink

awk -F "[\t ]" '{ $2=$1 "_" $2; print $1 "\t" $2 "\t" $3 "\t" $4 }' ${input_data}.map > temp.map
mv temp.map ${input_data}.map

# call my python script to write the phenotype codes into the .ped file
python $PBS_O_WORKDIR/pheno_lookup.py ../individual.list ${input_data}.ped ${input_data}.ped.out

mv ${input_data}.ped.out ${input_data}.ped

# make binary files
plink --file ${input_data} --out ${input_data} --make-bed --allow-extra-chr

# run association *without* population as covariate
plink --bfile ${input_data} --allow-no-sex --geno 0.50 --allow-extra-chr --model fisher --ci 0.95 --pfilter 0.5 --out ${input_data}.NO_COVAR --test-missing --real-ref-alleles

# run association *with* population as covariate
plink --bfile ${input_data} --allow-no-sex --geno 0.50 --allow-extra-chr --model fisher --ci 0.95 --pfilter 0.5 --out ${input_data}.POP_COVAR --test-missing --real-ref-alleles --covar plink_pheno_file.txt --covar-number 1

diff ${input_data}.NO_COVAR.model ${input_data}.POP_COVAR.model
