#!/bin/bash -login
#PBS -l nodes=1:ppn=1,walltime=04:00:00,mem=16gb
#PBS -N plink_bed
#PBS -o /mnt/research/efish/2015_genomic_data/scripts
#PBS -j oe
#PBS -M pitchers@msu.edu
#PBS -m abe
#PBS -r n

## Set up some variables
# where do the files live
#dir=/mnt/ls15/scratch/groups/efish/WILL/Pipeline8
dir=/mnt/ls15/scratch/groups/efish/WILL/Pipeline8/bionano

# load modules
cd ${dir}

module load plink/1.9


plink --file ${input_data} --out ${input_data} --make-bed --allow-extra-chr

# email user & start the next job
echo "." | mail -s "the plink_bed job is finished" ${USER}@msu.edu
cd $PBS_O_WORKDIR
qsub plink_fisher.qsub -v input_data=${input_data}

#Print out the statistics for this job
qstat -f ${PBS_JOBID}
