#!/bin/bash -login
#PBS -o /mnt/scratch/pitchers/eFISH/logfiles
#PBS -l nodes=1:ppn=1,walltime=04:00:00,mem=32gb
#PBS -N PLINK_fisher
#PBS -j oe
#PBS -M pitchers@msu.edu
#PBS -m abe
#PBS -r n

dir=/mnt/scratch/pitchers/eFISH/Analysis/

cd $dir

module load plink/1.07

mydata=`basename all_variants_merged_27_10_2015.vcf .vcf`

awk -F "[\t ]" '{ pop=substr( $1, 1, 4) } { if ( pop=="6494" || pop=="6496" || pop=="6497" || pop=="6498" || pop=="6499" || pop=="6500" || pop=="6501" || pop=="6502" || pop=="6597" || pop=="6598" || pop=="6599" || pop=="6602" || pop=="6603" || pop=="6604" || pop=="6605" || pop=="6619" || pop=="6620" || pop=="6621" || pop=="6622" || pop=="6623" || pop=="6624" || pop=="6625" || pop=="6626" || pop=="6627" ) {pheno="NP"} else if ( pop=="4004" || pop=="4006" || pop=="4018" || pop=="4019" || pop=="4027" || pop=="4029" ) { pheno="-9" } else {pheno="P"} } { print $1,'\t',$2,'\t',$3,'\t',$4,'\t',$5,pheno}' all_variants_merged_27_10_2015.fam > all_variants_merged_27_10_2015.fam.out

plink --bfile $mydata --fisher --out ${mydata}.out


echo "." | mail -s "The PLINK JOB is finishing" ${USER}@msu.edu
cd ${PBS_O_WORKDIR}
#    qsub nextjerb

#Print out the statistics for this job
qstat -f ${PBS_JOBID}
