#!/bin/bash -login
#PBS -l nodes=1:ppn=1,walltime=00:30:00,mem=32gb
#PBS -N Trimm_${n}
#PBS -j oe
#PBS -M pitchers@msu.edu
#PBS -m abe
#PBS -r n
#PBS -t 0-200

#Set manximum number of jobs for this run
MAXJOBID=256

#The JOBSCRIPT variable should be the name of _this_ script
JOBSCRIPT=trimmomatic_array.qsub

## Set up some variables
# where do the files live
dir=/mnt/scratch/pitchers/eFISH/Illumina_2015/GATK-compatible/

# Current job number
n=${PBS_ARRAYID}

# build a list of file names
cd ${dir}
myfiles=(*_R1_001.fastq.gz)

# unzip the focal gzip archive and its mate-pair
gunzip -c ${myfiles[${n}]} > `basename ${myfiles[${n}]} .gz`
gunzip -c `basename ${myfiles[${n}]} _R1_001.fastq.gz`_R2_001.fastq.gz > `basename ${myfiles[${n}]} _R1_001.fastq.gz`_R2_001.fastq

# pull out one element of the array at a time based on n
thisname=`basename ${myfiles[${n}]} _R1_001.fastq.gz`

# load required modules
module load Trimmomatic/0.32
module load Java

# Trimmomatic command
java -jar $TRIM/trimmomatic PE -threads 7 -phred33 ${thisname}_R1_001.fastq ${thisname}_R2_001.fastq ${thisname}_R1_pe.trimmed.fq ${thisname}_R1_se.trimmed.fq ${thisname}_R2_pe.trimmed.fq ${thisname}_R2_se.trimmed.fq ILLUMINACLIP:/mnt/home/pitchers/Illumina_adapters.fa:2:30:10 HEADCROP:10 MAXINFO:50:0.5

# Calculate next job to run
NEXT=$(( ${n} + 200 ))

#Check to see if next job is past the maximum job id, if so then submit the next unqueued job
if [ ${NEXT} -le ${MAXJOBID} ]
then
    cd ${PBS_O_WORKDIR}
    qsub -t ${NEXT} ${JOBSCRIPT}
fi

#Check to see if this is the last job, if so email me and submit the scritp for the next stage of the pipeline
if [ ${n} -eq ${MAXJOBID} ]
then
    echo "." | mail -s "The Trimmomatic JOB ARRAY is finishing" ${USER}@msu.edu
    cd ${PBS_O_WORKDIR}
    qsub alignment_array.qsub
fi

#Print out the statistics for this job
qstat -f ${PBS_JOBID}
