#!/bin/bash -login
#PBS -l nodes=1:ppn=8,walltime=00:30:00,mem=32gb
#PBS -N Trimm_${PBS_ARRAYID}
#PBS -j oe
#PBS -M pitchers@msu.edu
#PBS -m abe
#PBS -r n
#PBS -t 1-200

#Set manximum number of jobs for this run
MAXJOBID=256

#The JOBSCRIPT variable should be the name of this script
JOBSCRIPT=trimmomatic_array.qsub

## Set up some variables
# where do the files live
dir=/mnt/scratch/pitchers/eFISH/Illumina_2015/GATK-compatible/
# Current job number
n=${PBS_ARRAYID}
# build a list of file names
cd ${dir}
myfiles=(*_R1_001.fastq.gz)
gunzip -c ${myfiles[${PBS_ARRAYID}]} > `basename ${myfiles[${PBS_ARRAYID}]} .gz`
# pull out one element of the array at a time based on PBS_ARRAYID
thisname=`basename ${myfiles[${PBS_ARRAYID}]} _R1_001.fastq.gz`

module load Trimmomatic/0.32

# Trimmomatic
java -jar $TRIM/trimmomatic PE -threads 7 -phred33 ${thisname}_R1_001.fastq ${thisname}_R2_001.fastq ${thisname}_R1_pe.trimmed.fq ${thisname}_R1_se.trimmed.fq ${thisname}_R2_pe.trimmed.fq ${thisname}_R2_se.trimmed.fq ILLUMINACLIP:/mnt/home/pitchers/Illumina_adapters.fa:2:30:10 HEADCROP:10 MAXINFO:50:0.5

# Calculate next job to run
NEXT=$(( ${n} + 200 ))

#Check to see if next job is past the maximum job id
if [ ${NEXT} -le ${MAXJOBID} ]
then
    cd ${PBS_O_WORKDIR}
    qsub -t ${NEXT} ${JOBSCRIPT}
fi

#Check to see if this is the last job and email user
if [ ${n} -eq ${MAXJOBID} ]
then
    echo "." | mail -s "The Trimmomatic JOB ARRAY is finishing" ${USER}@msu.edu
    qsub alignment_array.qsub
fi

#Print out the statistics for this job
qstat -f ${PBS_JOBID}
