#!/bin/bash -login
#PBS -l nodes=1:ppn=4,walltime=04:00:00,mem=60gb
#PBS -N var2plink
#PBS -o /mnt/research/efish/2015_genomic_data/scripts
#PBS -j oe
#PBS -M pitchers@msu.edu
#PBS -m abe
#PBS -r n

## Set up some variables
# where do the files live
#dir=/mnt/scratch/pitchers/eFISH/Analysis/
dir=/mnt/ls15/scratch/groups/efish/WILL/
ref=/mnt/ls15/scratch/groups/efish/P_kings_genome/supercontigs.fasta
meta=/mnt/ls15/scratch/groups/efish/WILL/all_fish_phenotypes.fam

# load modules
cd ${dir}
#module load GATK/3.5.0
module load Java/1.8.0_31


# the call to GATK
java -Xmx60g -jar /mnt/home/pitchers/GenomeAnalysisTK.jar -T VariantsToBinaryPed \
               -R ${ref}  -V ${input_data}.vcf \
               -m ${meta} -mgq 0 \
               -bed ${input_data}.bed \
               -bim ${input_data}.bim \
               -fam ${input_data}.fam \
               --disable_auto_index_creation_and_locking_when_reading_rods


awk -F "[\t ]" '{ $2=$1 "_" $2; print $1 "\t" $2 "\t" $3 "\t" $4 }' ${input_data}.map > temp.map
mv temp.map ${input_data}.alt.map

# email user
echo "." | mail -s "the plink_prep job is finished" ${USER}@msu.edu
cd $PBS_O_WORKDIR



#Print out the statistics for this job
qstat -f ${PBS_JOBID}
