#!/bin/bash -login
#PBS -l nodes=1:ppn=4,walltime=04:00:00,mem=62gb
#PBS -N vcf_filter
#PBS -j oe
#PBS -M pitchers@msu.edu
#PBS -m abe
#PBS -r n

## Set up some variables

# where do the files live
dir=/mnt/ls15/scratch/groups/efish/WILL/V5-1_chunks/
ref=/mnt/scratch/pitchers/eFISH/P_kings_genome/supercontigs.fasta

# build a list of file names
cd ${dir}

module load GATK/3.5.0

### SNPs ###
## call to GATK – input vcf and output SNPs only
java -Xmx60g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T SelectVariants -R ${ref} -V ${input_data}.vcf \
						-selectType SNP -o ${input_data}.snps.vcf

## 
java -Xmx60g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T VariantFiltration -R ${ref} -V ${input_data}.snps.vcf \
#						--filterExpression "QD < 2.0 || FS > 60.0 || MQ < 40.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0" \
						--filterExpression "QD < 5.0 || FS > 30.0 || MQ < 20.0 || MQRankSum < -8.0 || ReadPosRankSum < -6.0" \
						-filterName "suggested_hard_filter" -o ${input_data}.filtered.2.snps.vcf \
						--setFilteredGtToNocall


### INDELS ###
## call to GATK – input vcf and output indels only
java -Xmx60g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T SelectVariants -R ${ref} -V ${input_data}.vcf \
                        -selectType INDEL -o ${input_data}.indels.vcf

##
java -Xmx60g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T VariantFiltration -R ${ref} -V ${input_data}.indels.vcf \
#						--filterExpression "QD < 2.0 || FS > 200.0 || ReadPosRankSum < -20.0" \
                        --filterExpression "QD < 5.0 || FS > 100.0 || ReadPosRankSum < -10.0" \
						-filterName "suggested_indel_filter" -o ${input_data}.filtered.2.indels.vcf \
						--setFilteredGtToNocall


echo "." | mail -s "The VCF stat job is finishing" ${USER}@msu.edu
cd ${PBS_O_WORKDIR}

#Print out the statistics for this job
qstat -f ${PBS_JOBID}
