#!/bin/bash -login
#PBS -l nodes=1:ppn=8,walltime=04:00:00,mem=120gb
#PBS -N VCFgeno_5-2
#PBS -j oe
#PBS -M pitchers@msu.edu
#PBS -m abe
#PBS -r n
#PBS -t 1-100

# Current job number
n=${PBS_ARRAYID}

#The JOBSCRIPT variable should be the name of this script
JOBSCRIPT=vcf_genotype_chunk_5-2_array.qsub

## Set up some variables
# where do the files live
#dir=/mnt/scratch/pitchers/eFISH/Analysis/
ref=/mnt/scratch/pitchers/eFISH/P_kings_genome/supercontigs.fasta
dir=/mnt/ls15/scratch/groups/efish/WILL/

cd ${dir}
mkdir -p V5-2_chunks

#Set manximum number of jobs for this run
MAXJOBID=`wc -l indices.list | cut -d' ' -f 1`

module load GATK/3.5.0

cd V5-2_chunks/

thesefish=(*/*slice_${n}.g.vcf)
samples=`for i in ${thesefish[@]} ; do echo --variant:VCF ${i} ; done | xargs`

# the call to the GATK CombineGVCFs
#java -Xmx60g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T CombineGVCFs \
#			-R ${ref} ${samples} --out all_fish_`date '+%m_%Y'`_slice_${n}.g.vcf

if [ ! -f all_fish_*_slice_${n}.vcf ]
then
	# now the slice has all fish, the call the GenotypeGVCFs
java -Xmx120g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T GenotypeGVCFs \
				-R ${ref} ${samples} -nt 8 \
				 -stand_call_conf 30 -stand_emit_conf 30 \
				--out all_fish_`date '+%m_%Y'`_slice_${n}.vcf \
				--disable_auto_index_creation_and_locking_when_reading_rods
fi


# Calculate next job to run
NEXT=$(( ${n} + 100 ))

#Check to see if next job is past the maximum job id
if [ ${NEXT} -le ${MAXJOBID} ]
then
    cd ${PBS_O_WORKDIR}
    qsub -t ${NEXT} ${JOBSCRIPT}
fi

#Check to see if this is the last job and email user
if [ ${n} -eq ${MAXJOBID} ]
then
    echo "." | mail -s "The vcf genotyping V5.2 ARRAY is finishing" ${USER}@msu.edu
    cd ${PBS_O_WORKDIR}
#	qsub plink_prep.qsub
fi

#Print out the statistics for this job
qstat -f ${PBS_JOBID}
