#!/bin/bash -login
#PBS -l nodes=1:ppn=4,walltime=06:00:00,mem=16gb
#PBS -N vcf_disco_${PBS_ARRAYID}
#PBS -j oe
#PBS -M pitchers@msu.edu
#PBS -o /mnt/research/efish/2015_genomic_data/scripts/
#PBS -m abe
#PBS -r n
#PBS -t 1-63
##### 0-200

#Set manximum number of jobs for this run
# MAXJOBID=767

#The JOBSCRIPT variable should be the name of this script
# JOBSCRIPT=vcf_discovery_array_boot.qsub

## Set up some variables
# where do the files live
dir=/mnt/scratch/pitchers/eFISH/Analysis/
ref=/mnt/scratch/pitchers/eFISH/P_kings_genome/supercontigs.fasta
# Current job number
n=${PBS_ARRAYID}
# build a list of file names
cd ${dir}
# filelist=(*recalibrated.boot.bam)
# thisfile=${filelist[${n}]}

# select a sample
individual=`head -${n} samples.list | tail -1`
sample=(${individual}*.boot.bam)
samples=`for i in ${sample[@]} ; do echo I=${i} ; done | xargs`

# module load GATK/3.4.46
module load GATK/3.5.0

# if [ ! -f `basename ${thisfile} .recalibrated.boot.bam`.raw_variants.boot.vcf ]
# then
# the call to the GATK HaplotypeCaller
java -Xmx10g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T HaplotypeCaller -R ${ref} -I ${samples} --genotyping_mode DISCOVERY -stand_emit_conf 10 -stand_call_conf 30 -o `basename ${individual} .recalibrated.boot.bam`.raw_variants.boot.vcf
# fi

# Calculate next job to run
# NEXT=$(( ${n} + 200 ))

#Check to see if next job is past the maximum job id
# if [ ${NEXT} -le ${MAXJOBID} ]
# then
#     cd ${PBS_O_WORKDIR}
#     qsub -t ${NEXT} ${JOBSCRIPT}
# fi

#Check to see if this is the last job and email user
# if [ ${n} -eq ${MAXJOBID} ]
# then
#     echo "." | mail -s "The vcf_discovery JOB ARRAY is finishing" ${USER}@msu.edu
#     cd ${PBS_O_WORKDIR}
#     # qsub compress_vcfs.qsub
# fi

#Print out the statistics for this job
qstat -f ${PBS_JOBID}
