#!/bin/bash -login
#PBS -l nodes=1:ppn=4,walltime=04:00:00,mem=60gb
#PBS -N VCFdisc_5-2
#PBS -j oe
#PBS -M pitchers@msu.edu
#PBS -m abe
#PBS -r n
#PBS -t 1-100

# which data?
thisfile=${input_data}

# Current job number
n=${PBS_ARRAYID}

#The JOBSCRIPT variable should be the name of this script
JOBSCRIPT=vcf_disco_chunk_5-2_array.qsub

## Set up some variables
# where do the files live
#dir=/mnt/scratch/pitchers/eFISH/Analysis/
ref=/mnt/scratch/pitchers/eFISH/P_kings_genome/supercontigs.fasta
dir=/mnt/ls15/scratch/groups/efish/WILL/

cd ${dir}
mkdir -p V5-2_chunks

#Set manximum number of jobs for this run
MAXJOBID=`wc -l indices.list | cut -d' ' -f 1`

module load GATK/3.5.0

# cut out a chunk
thisindex=`head -${n} indices.list | tail -1`

readarray thesefiles < samples.list

for thisfile in ${thesefiles[@]}
	do outputfilename=${thisfile}_`date '+%d_%m_%Y'`_slice_${n}.g.vcf

	if [ ! -f V5-2_chunks/${outputfilename} ] 
	then
	# # the call to the GATK HaplotypeCaller
	java -Xmx60g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T HaplotypeCaller \
				-R ${ref} -I ${thisfile}_all_libraries.bam \
				${thisindex} \
				--genotyping_mode DISCOVERY \
				-stand_emit_conf 10 -stand_call_conf 30 \
		        -o V5-2_chunks/${outputfilename} \
		        --output_mode EMIT_ALL_CONFIDENT_SITES \
			    --num_threads 1 --num_cpu_threads_per_data_thread 4 \
				--emitRefConfidence GVCF \
				--sample_name ${thisfile}
	fi
done

# Calculate next job to run
NEXT=$(( ${n} + 100 ))

#Check to see if next job is past the maximum job id
if [ ${NEXT} -le ${MAXJOBID} ]
then
    cd ${PBS_O_WORKDIR}
    qsub -t ${NEXT} ${JOBSCRIPT}
fi

#Check to see if this is the last job and email user
if [ ${n} -eq ${MAXJOBID} ]
then
    echo "." | mail -s "The vcf_discovery V5.2 ARRAY is finishing" ${USER}@msu.edu
    cd ${PBS_O_WORKDIR}

fi

#Print out the statistics for this job
qstat -f ${PBS_JOBID}
