#!/bin/bash -login
#PBS -l nodes=1:ppn=4,walltime=04:00:00,mem=62gb
#PBS -N VCF_filter
#PBS -j oe
#PBS -M pitchers@msu.edu
#PBS -m abe
#PBS -r n

# This script gets submitted thusly, e.g.: ` qsub -v input_data=all_fish_version_6-1,GQ=20 vcf_filter.qsub `

## Set up some variables – where do the files live
dir=/mnt/ls15/scratch/groups/efish/WILL/Pipeline6/Assoc/
ref=/mnt/scratch/pitchers/eFISH/P_kings_genome/supercontigs.fasta

cd ${dir}
module load GATK/3.7.0

### call to GATK – input vcf and output filtered vcf ###
#if [ ! -f ${input_data}.filtered.all_variants.GQ${GQ}.vcf ]
#	then
	### SNPs ###
	java -Xmx60g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T SelectVariants -R ${ref} -V ${input_data}.vcf \
						-selectType SNP  -nt 4  -o ${input_data}.snps.vcf

	java -Xmx60g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T VariantFiltration -R ${ref} -V ${input_data}.snps.vcf \
						--filterExpression "QD < 2.0 || FS > 60.0 || MQ < 40.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0" \
						-filterName "suggested_hard_filter" --setFilteredGtToNocall \
						--genotypeFilterExpression "GQ < ${GQ}" --genotypeFilterName "GQ${GQ}" \
						-o ${input_data}.filtered.snps.GQ${GQ}.vcf
	### INDELS ###
	java -Xmx60g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T SelectVariants -R ${ref} -V ${input_data}.vcf \
					   -selectType INDEL  -nt 4 -o ${input_data}.indels.vcf

	java -Xmx60g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T VariantFiltration -R ${ref} -V ${input_data}.indels.vcf \
						--filterExpression "QD < 2.0 || FS > 200.0 || ReadPosRankSum < -20.0" \
						-filterName "suggested_indel_filter" --setFilteredGtToNocall \
						--genotypeFilterExpression "GQ < ${GQ}" --genotypeFilterName "GQ${GQ}" \
						-o ${input_data}.filtered.indels.GQ${GQ}.vcf

    rm ${input_data}.snps.vcf  ${input_data}.indels.vcf

	### merge ###
	java -Xmx60g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T CombineVariants -R ${ref} \
						--variant ${input_data}.filtered.snps.GQ${GQ}.vcf \
						--variant ${input_data}.filtered.indels.GQ${GQ}.vcf \
						-o ${input_data}.filtered.all_variants.GQ${GQ}.vcf \
#						-genotypeMergeOptions UNIQIFY

#	rm ${input_data}.filtered.snps.GQ${GQ}.vcf  ${input_data}.filtered.indels.GQ${GQ}.vcf
#fi

echo "." | mail -s "The VCF filtering job is finishing" ${USER}@msu.edu
cd ${PBS_O_WORKDIR}
qsub next job here...

#Print out the statistics for this job
qstat -f ${PBS_JOBID}
