#!/bin/bash -login
#PBS -l nodes=1:ppn=28,walltime=04:00:00,mem=120gb
#PBS -N vcf_stat
#PBS -j oe
#PBS -M pitchers@msu.edu
#PBS -m abe
#PBS -r n

## Set up some variables

# where do the files live
dir=/mnt/ls15/scratch/groups/efish/WILL/Pipeline8
#dir=/mnt/ls15/scratch/groups/efish/WILL/Pipeline8/bionano


# build a list of file names
cd ${dir}
module load vcftools/0.1.14


#vcftools --vcf ${input_data}.vcf --out ${input_data} --depth
#vcftools --vcf ${input_data}.vcf --out ${input_data} --site-depth
#vcftools --vcf ${input_data}.vcf --out ${input_data} --site-mean-depth
#vcftools --vcf ${input_data}.vcf --out ${input_data} --geno-depth
#vcftools --vcf ${input_data}.vcf --out ${input_data} --site-quality
vcftools --vcf ${input_data}.vcf --out ${input_data} --geno-r2


echo "." | mail -s "The VCF stat job is finishing" ${USER}@msu.edu
cd ${PBS_O_WORKDIR}

#Print out the statistics for this job
qstat -f ${PBS_JOBID}

