#!/bin/bash -login
#PBS -l nodes=1:ppn=4,walltime=00:30:00,mem=32gb
#PBS -o /mnt/research/efish/2015_genomic_data/scripts
#PBS -N vcf_sample_merge
#PBS -j oe
#PBS -M pitchers@msu.edu
#PBS -m abe
#PBS -r n
#PBS -t 1-63

## Set up some variables
# where do the files live
dir=/mnt/scratch/pitchers/eFISH/Analysis/
ref=/mnt/scratch/pitchers/eFISH/P_kings_genome/supercontigs.fasta

# Current job number
n=${PBS_ARRAYID}
MAXJOBID=63

# load modules
cd ${dir}
module load tabix/0.2.6
module load vcftools/0.1.9
module load GATK/3.4.46

# make sure that the samples.list file is available
if [ ! -f samples.list ]
  then cp /mnt/research/efish/2015_genomic_data/samples.list ./
fi

sample=(`head -${n} samples.list | tail -1 `*raw_variants.vcf)
samples=`for i in ${sample[@]} ; do echo --variant $i ; done | xargs`

# the call to VCF tools with `remove-dulpicates` on for merging winth sample
# vcf-merge --remove-duplicates `head -${n} samples.list | tail -1 `*raw_variants.vcf.gz | bgzip -c > `head -${n} samples.list | tail -1 `_all_libraries.vcf.gz

# the call to GATK
java -Xmx30g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T CombineVariants -R ${ref} ${samples} -o `head -${n} samples.list | tail -1 `_all_libraries.vcf #--genotypemergeoption UNIQUIFY

# re-indexing
tabix `head -${n} samples.list | tail -1 `_all_libraries.vcf

#Check to see if this is the last job and email user
if [ ${n} -eq ${MAXJOBID} ]
then
    echo "." | mail -s "The vcf merging sample ARRAY is finishing" ${USER}@msu.edu
    cd $PBS_O_WORKDIR
    # qsub merge_all_vcfs.qsub
fi

#Print out the statistics for this job
qstat -f ${PBS_JOBID}
